# cloudbuild.yaml
substitutions:
  _SERVICE_NAME: ""
  _REGION: ""
  _IMAGE: ""

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_IMAGE} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --set-secrets="SLACK_BOT_TOKEN=${_SERVICE_NAME}-slackbot-token:latest" \
          --set-secrets="OPENAI_API_KEY=${_SERVICE_NAME}-openai-api-key:latest" \
          --set-secrets="SLACK_SIGNING_SECRET=${_SERVICE_NAME}-slack-signing-secret:latest"

timeout: 900s

